Remove tabs in embedded python snippets
Having tabs instead of spaces raise the following error when copy/pasting in Python 3: 

```bash
$ python3 /tmp/test.py
  File "/tmp/test.py", line 6
    a = a - b
            ^
TabError: inconsistent use of tabs and spaces in indentation
```